name: weather2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - argon2-cffi=20.1.0
  - asciitree=0.3.3
  - astropy=4.0.3
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - bokeh=2.2.3
  - bottleneck=1.3.2
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cartopy=0.18.0
  - cdo=1.9.8
  - certifi=2020.12.5
  - cffi=1.14.4
  - cfgrib=0.9.8.5
  - cfitsio=3.470
  - cftime=1.3.0
  - click=7.1.2
  - cloudpickle=1.6.0
  - cudatoolkit=10.2.89
  - curl=7.71.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2.30.0
  - dask-core=2.30.0
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - distributed=2.30.1
  - eccodes=2.19.1
  - entrypoints=0.3
  - expat=2.2.10
  - fasteners=0.14.1
  - fftw=3.3.8
  - fontconfig=2.13.0
  - freetype=2.10.4
  - fsspec=0.8.4
  - geos=3.8.1
  - glib=2.66.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - healpy=1.14.0
  - heapdict=1.0.1
  - icu=58.2
  - importlib-metadata=3.3.0
  - importlib_metadata=3.3.0
  - iniconfig=1.1.1
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.2
  - jasper=1.900.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - joblib=1.0.1
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.7.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libaec=1.0.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libiconv=1.16
  - libllvm10=10.0.1
  - libnetcdf=4.7.4
  - libnghttp2=1.41.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libxcb=1.14
  - libxml2=2.9.10
  - llvmlite=0.36.0
  - locket=0.2.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - monotonic=1.5
  - more-itertools=8.6.0
  - msgpack-python=1.0.0
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - netcdf4=1.5.3
  - ninja=1.10.2
  - notebook=6.1.6
  - numba=0.53.0
  - numcodecs=0.7.3
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1j
  - ossuuid=1.6.2
  - packaging=20.7
  - pandas=1.0.1
  - pandoc=2.11.3.2
  - pandocfilters=1.4.2
  - parso=0.7.0
  - partd=1.1.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.3.1
  - pluggy=0.13.1
  - proj=7.1.1
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - properscoring=0.1
  - psutil=5.7.3
  - ptyprocess=0.6.0
  - py=1.9.0
  - pycparser=2.20
  - pygments=2.7.3
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pyshp=2.1.2
  - pytest=6.1.2
  - pytest-runner=5.2
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytorch=1.7.0
  - pytz=2020.4
  - pyyaml=5.3.1
  - pyzmq=20.0.0
  - qt=5.9.7
  - readline=8.0
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - send2trash=1.5.0
  - setuptools=51.0.0
  - shapely=1.7.1
  - sip=4.19.13
  - six=1.15.0
  - sortedcontainers=2.3.0
  - sqlite=3.33.0
  - tabulate=0.8.9
  - tbb=2020.2
  - tblib=1.6.0
  - terminado=0.9.1
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.2
  - toolz=0.11.1
  - torchaudio=0.7.0
  - torchvision=0.8.1
  - tornado=6.1
  - tqdm=4.54.1
  - traitlets=5.0.5
  - trimesh=3.8.19
  - typing_extensions=3.7.4.3
  - udunits2=2.2.27.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.1
  - widgetsnbextension=3.5.1
  - xarray=0.16.2
  - xhistogram=0.1.2
  - xskillscore=0.0.19
  - xz=5.2.5
  - yaml=0.2.5
  - zarr=2.6.1
  - zeromq=4.3.3
  - zict=2.0.0
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - dataclasses==0.6
    - future==0.18.2
    - gpytorch==1.4.0
    - pygsp==0.5.1
    - rechunker==0.3.3
    - sparselinear==0.0.5
    - torch-scatter==2.0.6
    - torch-sparse==0.6.9
